spring:
  application:
    name: Eventos Spring
  datasource:
    url: jdbc:mariadb://localhost:3306/gestion_eventos_login
    username: root
    password: 
    # url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
    # username: ${DB_USER}
    # password: ${DB_PASS}
    driver-class-name: org.mariadb.jdbc.Driver
  web:
    resources:
      static-locations: file:public
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: afsdfasrth
  # secret: ${JWT_SECRET}
